// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cart.sql

package db

import (
	"context"
)

const clearUserCart = `-- name: ClearUserCart :exec
DELETE FROM carts
WHERE user_id = $1
`

type ClearUserCartParams struct {
	UserID int64
}

func (q *Queries) ClearUserCart(ctx context.Context, arg ClearUserCartParams) error {
	_, err := q.db.ExecContext(ctx, clearUserCart, arg.UserID)
	return err
}

const createCart = `-- name: CreateCart :one
INSERT INTO carts (
  user_id, product_id, quantity
) VALUES (
  $1, $2, $3
)
ON CONFLICT (user_id, product_id)
DO UPDATE SET 
quantity = carts.quantity + EXCLUDED.quantity,
updated_at = now()
RETURNING user_id, product_id, quantity, created_at, updated_at
`

type CreateCartParams struct {
	UserID    int64
	ProductID int64
	Quantity  int64
}

func (q *Queries) CreateCart(ctx context.Context, arg CreateCartParams) (Cart, error) {
	row := q.db.QueryRowContext(ctx, createCart, arg.UserID, arg.ProductID, arg.Quantity)
	var i Cart
	err := row.Scan(
		&i.UserID,
		&i.ProductID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserCart = `-- name: GetUserCart :many
SELECT user_id, product_id, quantity, created_at, updated_at FROM carts
WHERE user_id = $1
ORDER BY updated_at DESC
`

type GetUserCartParams struct {
	UserID int64
}

func (q *Queries) GetUserCart(ctx context.Context, arg GetUserCartParams) ([]Cart, error) {
	rows, err := q.db.QueryContext(ctx, getUserCart, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cart
	for rows.Next() {
		var i Cart
		if err := rows.Scan(
			&i.UserID,
			&i.ProductID,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFromCart = `-- name: RemoveFromCart :exec
DELETE FROM carts
WHERE user_id = $1 AND product_id = $2
`

type RemoveFromCartParams struct {
	UserID    int64
	ProductID int64
}

func (q *Queries) RemoveFromCart(ctx context.Context, arg RemoveFromCartParams) error {
	_, err := q.db.ExecContext(ctx, removeFromCart, arg.UserID, arg.ProductID)
	return err
}

const updateCartQuantity = `-- name: UpdateCartQuantity :one
UPDATE carts
SET 
quantity = $3,
updated_at = now()
WHERE user_id = $1 AND product_id = $2
RETURNING user_id, product_id, quantity, created_at, updated_at
`

type UpdateCartQuantityParams struct {
	UserID    int64
	ProductID int64
	Quantity  int64
}

func (q *Queries) UpdateCartQuantity(ctx context.Context, arg UpdateCartQuantityParams) (Cart, error) {
	row := q.db.QueryRowContext(ctx, updateCartQuantity, arg.UserID, arg.ProductID, arg.Quantity)
	var i Cart
	err := row.Scan(
		&i.UserID,
		&i.ProductID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
