// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Cart struct {
	UserID    int64
	ProductID int64
	Quantity  int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Order struct {
	ID          int64
	UserID      int64
	TotalAmount int64
	// PENDING | SHIPPING | DELIVERED
	Status          string
	ShippingAddress string
	CustomerPhone   string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type OrderItem struct {
	ID        int64
	OrderID   int64
	ProductID int64
	Quantity  int64
	Price     int64
}
