// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Cart struct {
	ID        int64
	UserID    int64
	ProductID int64
	Quantity  int64
	UpdatedAt pgtype.Timestamptz
}

type Order struct {
	ID          int64
	UserID      int64
	TotalAmount int64
	// PENDING | SHIPPING | DELIVERED
	Status          string
	ShippingAddress string
	CustomerPhone   string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type OrderItem struct {
	ID        int64
	OrderID   int64
	ProductID int64
	Quantity  int64
	Price     int64
}
