// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order.sql

package db

import (
	"context"
	"time"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
  user_id, total_amount, status, shipping_address, customer_phone
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, user_id, total_amount, status, shipping_address, customer_phone, created_at, updated_at
`

type CreateOrderParams struct {
	UserID          int64
	TotalAmount     int64
	Status          string
	ShippingAddress string
	CustomerPhone   string
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder,
		arg.UserID,
		arg.TotalAmount,
		arg.Status,
		arg.ShippingAddress,
		arg.CustomerPhone,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TotalAmount,
		&i.Status,
		&i.ShippingAddress,
		&i.CustomerPhone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, user_id, total_amount, status, shipping_address, customer_phone, created_at, updated_at FROM orders
WHERE id = $1 LIMIT 1
`

type GetOrderParams struct {
	ID int64
}

func (q *Queries) GetOrder(ctx context.Context, arg GetOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrder, arg.ID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TotalAmount,
		&i.Status,
		&i.ShippingAddress,
		&i.CustomerPhone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserOrders = `-- name: ListUserOrders :many
SELECT id, user_id, total_amount, status, shipping_address, customer_phone, created_at FROM orders
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUserOrdersParams struct {
	UserID int64
	Limit  int32
	Offset int32
}

type ListUserOrdersRow struct {
	ID              int64
	UserID          int64
	TotalAmount     int64
	Status          string
	ShippingAddress string
	CustomerPhone   string
	CreatedAt       time.Time
}

func (q *Queries) ListUserOrders(ctx context.Context, arg ListUserOrdersParams) ([]ListUserOrdersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserOrders, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserOrdersRow
	for rows.Next() {
		var i ListUserOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TotalAmount,
			&i.Status,
			&i.ShippingAddress,
			&i.CustomerPhone,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET 
    status = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, total_amount, status, shipping_address, customer_phone, created_at, updated_at
`

type UpdateOrderStatusParams struct {
	ID     int64
	Status string
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, updateOrderStatus, arg.ID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TotalAmount,
		&i.Status,
		&i.ShippingAddress,
		&i.CustomerPhone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
