// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: category.sql

package db

import (
	"context"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (
  name , slug
) VALUES (
  $1, $2
)
RETURNING id, name, slug
`

type CreateCategoryParams struct {
	Name string
	Slug string
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory, arg.Name, arg.Slug)
	var i Category
	err := row.Scan(&i.ID, &i.Name, &i.Slug)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories
WHERE name = $1
`

type DeleteCategoryParams struct {
	Name string
}

func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, arg.Name)
	return err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, name, slug FROM categories
WHERE id = $1 LIMIT 1
`

type GetCategoryByIDParams struct {
	ID int64
}

func (q *Queries) GetCategoryByID(ctx context.Context, arg GetCategoryByIDParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryByID, arg.ID)
	var i Category
	err := row.Scan(&i.ID, &i.Name, &i.Slug)
	return i, err
}

const getCategoryByName = `-- name: GetCategoryByName :one
SELECT id, name, slug FROM categories
WHERE name = $1 LIMIT 1
`

type GetCategoryByNameParams struct {
	Name string
}

func (q *Queries) GetCategoryByName(ctx context.Context, arg GetCategoryByNameParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryByName, arg.Name)
	var i Category
	err := row.Scan(&i.ID, &i.Name, &i.Slug)
	return i, err
}

const getCategoryBySlug = `-- name: GetCategoryBySlug :one
SELECT id, name, slug FROM categories
WHERE slug = $1 LIMIT 1
`

type GetCategoryBySlugParams struct {
	Slug string
}

func (q *Queries) GetCategoryBySlug(ctx context.Context, arg GetCategoryBySlugParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryBySlug, arg.Slug)
	var i Category
	err := row.Scan(&i.ID, &i.Name, &i.Slug)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, slug FROM categories
ORDER BY name
LIMIT $1
OFFSET $2
`

type ListCategoriesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Name, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :exec
UPDATE categories
  set name = $2,
  slug = $3
WHERE id = $1
`

type UpdateCategoryParams struct {
	ID   int64
	Name string
	Slug string
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error {
	_, err := q.db.ExecContext(ctx, updateCategory, arg.ID, arg.Name, arg.Slug)
	return err
}
