// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/sqlc-dev/pqtype"
)

type Category struct {
	ID   int64
	Name string
	Slug string
}

type Product struct {
	ID         int64
	CategoryID int64
	Name       string
	Slug       string
	Sku        string
	Price      int64
	Stock      int32
	Attributes pqtype.NullRawMessage
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type ProductImage struct {
	ID        int64
	ProductID int64
	ImageUrl  string
	IsPrimary bool
}
