// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product.sql

package db

import (
	"context"
	"time"

	"github.com/sqlc-dev/pqtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    category_id, name, slug, sku, price, stock, attributes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, category_id, name, slug, sku, price, stock, attributes, created_at, updated_at
`

type CreateProductParams struct {
	CategoryID int64
	Name       string
	Slug       string
	Sku        string
	Price      int64
	Stock      int32
	Attributes pqtype.NullRawMessage
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.CategoryID,
		arg.Name,
		arg.Slug,
		arg.Sku,
		arg.Price,
		arg.Stock,
		arg.Attributes,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Sku,
		&i.Price,
		&i.Stock,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products
WHERE name = $1
`

type DeleteProductParams struct {
	Name string
}

func (q *Queries) DeleteProduct(ctx context.Context, arg DeleteProductParams) error {
	_, err := q.db.ExecContext(ctx, deleteProduct, arg.Name)
	return err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, category_id, name, slug, sku, price, stock, attributes, created_at, updated_at
FROM products
WHERE id = $1 LIMIT 1
`

type GetProductByIDParams struct {
	ID int64
}

func (q *Queries) GetProductByID(ctx context.Context, arg GetProductByIDParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByID, arg.ID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Sku,
		&i.Price,
		&i.Stock,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductByName = `-- name: GetProductByName :one
SELECT id, category_id, name, slug, sku, price, stock, attributes, created_at, updated_at
FROM products
WHERE name = $1 LIMIT 1
`

type GetProductByNameParams struct {
	Name string
}

func (q *Queries) GetProductByName(ctx context.Context, arg GetProductByNameParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByName, arg.Name)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Sku,
		&i.Price,
		&i.Stock,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductBySlug = `-- name: GetProductBySlug :one
SELECT id, category_id, name, slug, sku, price, stock, attributes, created_at, updated_at
FROM products
WHERE slug = $1 LIMIT 1
`

type GetProductBySlugParams struct {
	Slug string
}

func (q *Queries) GetProductBySlug(ctx context.Context, arg GetProductBySlugParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductBySlug, arg.Slug)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Sku,
		&i.Price,
		&i.Stock,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, category_id, name, slug, sku, price, stock, created_at
FROM products
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListProductsParams struct {
	Limit  int32
	Offset int32
}

type ListProductsRow struct {
	ID         int64
	CategoryID int64
	Name       string
	Slug       string
	Sku        string
	Price      int64
	Stock      int32
	CreatedAt  time.Time
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
			&i.Sku,
			&i.Price,
			&i.Stock,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByCategory = `-- name: ListProductsByCategory :many
SELECT id, category_id, name, slug, sku, price, stock, created_at
FROM products
WHERE category_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListProductsByCategoryParams struct {
	CategoryID int64
	Limit      int32
	Offset     int32
}

type ListProductsByCategoryRow struct {
	ID         int64
	CategoryID int64
	Name       string
	Slug       string
	Sku        string
	Price      int64
	Stock      int32
	CreatedAt  time.Time
}

func (q *Queries) ListProductsByCategory(ctx context.Context, arg ListProductsByCategoryParams) ([]ListProductsByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listProductsByCategory, arg.CategoryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsByCategoryRow
	for rows.Next() {
		var i ListProductsByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
			&i.Sku,
			&i.Price,
			&i.Stock,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET 
    category_id = $2,
    name = $3,
    slug = $4,
    sku = $5,
    price = $6,
    stock = $7,
    attributes = $8,
    updated_at = now()
WHERE id = $1
RETURNING id, category_id, name, slug, sku, price, stock, attributes, created_at, updated_at
`

type UpdateProductParams struct {
	ID         int64
	CategoryID int64
	Name       string
	Slug       string
	Sku        string
	Price      int64
	Stock      int32
	Attributes pqtype.NullRawMessage
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, updateProduct,
		arg.ID,
		arg.CategoryID,
		arg.Name,
		arg.Slug,
		arg.Sku,
		arg.Price,
		arg.Stock,
		arg.Attributes,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Sku,
		&i.Price,
		&i.Stock,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProductStock = `-- name: UpdateProductStock :one
UPDATE products
SET 
    stock = stock + $2,
    updated_at = now()
WHERE name = $1
RETURNING id, category_id, name, slug, sku, price, stock, attributes, created_at, updated_at
`

type UpdateProductStockParams struct {
	Name  string
	Stock int32
}

func (q *Queries) UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, updateProductStock, arg.Name, arg.Stock)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Sku,
		&i.Price,
		&i.Stock,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
