// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_image.sql

package db

import (
	"context"
)

const addProductImage = `-- name: AddProductImage :one
INSERT INTO product_images (
    product_id, image_url, is_primary
) VALUES (
    $1, $2, $3
)
RETURNING id, product_id, image_url, is_primary
`

type AddProductImageParams struct {
	ProductID int64
	ImageUrl  string
	IsPrimary bool
}

func (q *Queries) AddProductImage(ctx context.Context, arg AddProductImageParams) (ProductImage, error) {
	row := q.db.QueryRowContext(ctx, addProductImage, arg.ProductID, arg.ImageUrl, arg.IsPrimary)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ImageUrl,
		&i.IsPrimary,
	)
	return i, err
}

const deleteProductImage = `-- name: DeleteProductImage :exec
DELETE FROM product_images
WHERE id = $1 AND product_id = $2
`

type DeleteProductImageParams struct {
	ID        int64
	ProductID int64
}

func (q *Queries) DeleteProductImage(ctx context.Context, arg DeleteProductImageParams) error {
	_, err := q.db.ExecContext(ctx, deleteProductImage, arg.ID, arg.ProductID)
	return err
}

const getProductImages = `-- name: GetProductImages :many
SELECT id, product_id, image_url, is_primary
FROM product_images
WHERE product_id = $1
ORDER BY is_primary DESC, id ASC
`

type GetProductImagesParams struct {
	ProductID int64
}

func (q *Queries) GetProductImages(ctx context.Context, arg GetProductImagesParams) ([]ProductImage, error) {
	rows, err := q.db.QueryContext(ctx, getProductImages, arg.ProductID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductImage
	for rows.Next() {
		var i ProductImage
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.ImageUrl,
			&i.IsPrimary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetPrimaryImage = `-- name: ResetPrimaryImage :exec
UPDATE product_images
SET is_primary = false
WHERE product_id = $1
`

type ResetPrimaryImageParams struct {
	ProductID int64
}

func (q *Queries) ResetPrimaryImage(ctx context.Context, arg ResetPrimaryImageParams) error {
	_, err := q.db.ExecContext(ctx, resetPrimaryImage, arg.ProductID)
	return err
}

const setPrimaryImage = `-- name: SetPrimaryImage :one
UPDATE product_images
SET is_primary = true
WHERE id = $1 AND product_id = $2
RETURNING id, product_id, image_url, is_primary
`

type SetPrimaryImageParams struct {
	ID        int64
	ProductID int64
}

func (q *Queries) SetPrimaryImage(ctx context.Context, arg SetPrimaryImageParams) (ProductImage, error) {
	row := q.db.QueryRowContext(ctx, setPrimaryImage, arg.ID, arg.ProductID)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ImageUrl,
		&i.IsPrimary,
	)
	return i, err
}
