// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    category_id, name, slug, sku, price, stock, attributes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, category_id, name, slug, sku, price, stock, attributes, created_at, updated_at
`

type CreateProductParams struct {
	CategoryID int64
	Name       string
	Slug       string
	Sku        string
	Price      int64
	Stock      int32
	Attributes []byte
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.CategoryID,
		arg.Name,
		arg.Slug,
		arg.Sku,
		arg.Price,
		arg.Stock,
		arg.Attributes,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Sku,
		&i.Price,
		&i.Stock,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products
WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const getProductById = `-- name: GetProductById :one
SELECT id, category_id, name, slug, sku, price, stock, attributes, created_at, updated_at
FROM products
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProductById(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRow(ctx, getProductById, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Sku,
		&i.Price,
		&i.Stock,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductBySlug = `-- name: GetProductBySlug :one
SELECT id, category_id, name, slug, sku, price, stock, attributes, created_at, updated_at
FROM products
WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetProductBySlug(ctx context.Context, slug string) (Product, error) {
	row := q.db.QueryRow(ctx, getProductBySlug, slug)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Sku,
		&i.Price,
		&i.Stock,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, category_id, name, slug, sku, price, stock, created_at
FROM products
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListProductsParams struct {
	Limit  int32
	Offset int32
}

type ListProductsRow struct {
	ID         int64
	CategoryID int64
	Name       string
	Slug       string
	Sku        string
	Price      int64
	Stock      int32
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
			&i.Sku,
			&i.Price,
			&i.Stock,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByCategory = `-- name: ListProductsByCategory :many
SELECT id, category_id, name, slug, sku, price, stock, created_at
FROM products
WHERE category_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListProductsByCategoryParams struct {
	CategoryID int64
	Limit      int32
	Offset     int32
}

type ListProductsByCategoryRow struct {
	ID         int64
	CategoryID int64
	Name       string
	Slug       string
	Sku        string
	Price      int64
	Stock      int32
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) ListProductsByCategory(ctx context.Context, arg ListProductsByCategoryParams) ([]ListProductsByCategoryRow, error) {
	rows, err := q.db.Query(ctx, listProductsByCategory, arg.CategoryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsByCategoryRow
	for rows.Next() {
		var i ListProductsByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
			&i.Sku,
			&i.Price,
			&i.Stock,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET 
    category_id = $2,
    name = $3,
    slug = $4,
    sku = $5,
    price = $6,
    stock = $7,
    attributes = $8,
    updated_at = now()
WHERE id = $1
RETURNING id, category_id, name, slug, sku, price, stock, attributes, updated_at
`

type UpdateProductParams struct {
	ID         int64
	CategoryID int64
	Name       string
	Slug       string
	Sku        string
	Price      int64
	Stock      int32
	Attributes []byte
}

type UpdateProductRow struct {
	ID         int64
	CategoryID int64
	Name       string
	Slug       string
	Sku        string
	Price      int64
	Stock      int32
	Attributes []byte
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (UpdateProductRow, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.CategoryID,
		arg.Name,
		arg.Slug,
		arg.Sku,
		arg.Price,
		arg.Stock,
		arg.Attributes,
	)
	var i UpdateProductRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Sku,
		&i.Price,
		&i.Stock,
		&i.Attributes,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProductStock = `-- name: UpdateProductStock :one
UPDATE products
SET 
    stock = stock + $2,
    updated_at = now()
WHERE id = $1
RETURNING id, name, stock
`

type UpdateProductStockParams struct {
	ID    int64
	Stock int32
}

type UpdateProductStockRow struct {
	ID    int64
	Name  string
	Stock int32
}

func (q *Queries) UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) (UpdateProductStockRow, error) {
	row := q.db.QueryRow(ctx, updateProductStock, arg.ID, arg.Stock)
	var i UpdateProductStockRow
	err := row.Scan(&i.ID, &i.Name, &i.Stock)
	return i, err
}
