// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Role struct {
	ID   int64
	Name string
}

type User struct {
	ID           int64
	Email        string
	PasswordHash string
	Fullname     string
	RoleID       int64
	IsActive     bool
	IsVerified   bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type UserToken struct {
	ID           int64
	UserID       int64
	RefreshToken string
	ExpiresAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}
