// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Role struct {
	ID          string
	Description string
}

type User struct {
	ID           int64
	Email        string
	PasswordHash string
	Fullname     string
	RoleID       string
	IsActive     bool
	IsVerified   bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type UserToken struct {
	ID           int64
	UserID       int64
	RefreshToken string
	ExpiresAt    time.Time
	CreatedAt    time.Time
}
