// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: role.sql

package db

import (
	"context"
)

const createRole = `-- name: CreateRole :one
INSERT INTO roles (
  id,
  description
) VALUES (
  $1, $2
)
ON CONFLICT (id)
DO UPDATE SET id = EXCLUDED.id
RETURNING id, description
`

type CreateRoleParams struct {
	ID          string
	Description string
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRowContext(ctx, createRole, arg.ID, arg.Description)
	var i Role
	err := row.Scan(&i.ID, &i.Description)
	return i, err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM roles
WHERE id = $1
`

type DeleteRoleParams struct {
	ID string
}

func (q *Queries) DeleteRole(ctx context.Context, arg DeleteRoleParams) error {
	_, err := q.db.ExecContext(ctx, deleteRole, arg.ID)
	return err
}

const getRole = `-- name: GetRole :one
SELECT id, description FROM roles
WHERE id = $1 LIMIT 1
`

type GetRoleParams struct {
	ID string
}

func (q *Queries) GetRole(ctx context.Context, arg GetRoleParams) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRole, arg.ID)
	var i Role
	err := row.Scan(&i.ID, &i.Description)
	return i, err
}

const listRoles = `-- name: ListRoles :many
SELECT id, description FROM roles
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListRolesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListRoles(ctx context.Context, arg ListRolesParams) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, listRoles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.ID, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRole = `-- name: UpdateRole :one
UPDATE roles
set description = $2
WHERE id = $1
RETURNING id, description
`

type UpdateRoleParams struct {
	ID          string
	Description string
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error) {
	row := q.db.QueryRowContext(ctx, updateRole, arg.ID, arg.Description)
	var i Role
	err := row.Scan(&i.ID, &i.Description)
	return i, err
}
