// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_token.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserToken = `-- name: CreateUserToken :one
INSERT INTO user_tokens (
  user_id, refresh_token, expires_at
) VALUES (
  $1, $2, $3
)
RETURNING id, user_id, refresh_token, expires_at, created_at
`

type CreateUserTokenParams struct {
	UserID       int64
	RefreshToken string
	ExpiresAt    pgtype.Timestamptz
}

func (q *Queries) CreateUserToken(ctx context.Context, arg CreateUserTokenParams) (UserToken, error) {
	row := q.db.QueryRow(ctx, createUserToken, arg.UserID, arg.RefreshToken, arg.ExpiresAt)
	var i UserToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAllUserTokens = `-- name: DeleteAllUserTokens :exec
DELETE FROM user_tokens
WHERE user_id = $1
`

func (q *Queries) DeleteAllUserTokens(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteAllUserTokens, userID)
	return err
}

const deleteExpiredTokens = `-- name: DeleteExpiredTokens :exec
DELETE FROM user_tokens
WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredTokens)
	return err
}

const deleteUserToken = `-- name: DeleteUserToken :exec
DELETE FROM user_tokens
WHERE refresh_token = $1
`

func (q *Queries) DeleteUserToken(ctx context.Context, refreshToken string) error {
	_, err := q.db.Exec(ctx, deleteUserToken, refreshToken)
	return err
}

const getUserToken = `-- name: GetUserToken :one
SELECT id, user_id, refresh_token, expires_at, created_at FROM user_tokens
WHERE refresh_token = $1 LIMIT 1
`

func (q *Queries) GetUserToken(ctx context.Context, refreshToken string) (UserToken, error) {
	row := q.db.QueryRow(ctx, getUserToken, refreshToken)
	var i UserToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
