// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_token.sql

package db

import (
	"context"
	"time"
)

const createUserToken = `-- name: CreateUserToken :one
INSERT INTO user_tokens (
  user_id, refresh_token, expires_at
) VALUES (
  $1, $2, $3
)
RETURNING id, user_id, refresh_token, expires_at, created_at
`

type CreateUserTokenParams struct {
	UserID       int64
	RefreshToken string
	ExpiresAt    time.Time
}

func (q *Queries) CreateUserToken(ctx context.Context, arg CreateUserTokenParams) (UserToken, error) {
	row := q.db.QueryRowContext(ctx, createUserToken, arg.UserID, arg.RefreshToken, arg.ExpiresAt)
	var i UserToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAllUserTokens = `-- name: DeleteAllUserTokens :exec
DELETE FROM user_tokens
WHERE user_id = $1
`

type DeleteAllUserTokensParams struct {
	UserID int64
}

func (q *Queries) DeleteAllUserTokens(ctx context.Context, arg DeleteAllUserTokensParams) error {
	_, err := q.db.ExecContext(ctx, deleteAllUserTokens, arg.UserID)
	return err
}

const deleteExpiredTokens = `-- name: DeleteExpiredTokens :exec
DELETE FROM user_tokens
WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredTokens(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredTokens)
	return err
}

const deleteUserToken = `-- name: DeleteUserToken :exec
DELETE FROM user_tokens
WHERE refresh_token = $1
`

type DeleteUserTokenParams struct {
	RefreshToken string
}

func (q *Queries) DeleteUserToken(ctx context.Context, arg DeleteUserTokenParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserToken, arg.RefreshToken)
	return err
}

const getUserToken = `-- name: GetUserToken :one
SELECT id, user_id, refresh_token, expires_at, created_at FROM user_tokens
WHERE refresh_token = $1 LIMIT 1
`

type GetUserTokenParams struct {
	RefreshToken string
}

func (q *Queries) GetUserToken(ctx context.Context, arg GetUserTokenParams) (UserToken, error) {
	row := q.db.QueryRowContext(ctx, getUserToken, arg.RefreshToken)
	var i UserToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
