// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  email, password_hash, fullname, role_id, is_active, is_verified
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, email, password_hash, fullname, role_id, is_active, is_verified, created_at, updated_at
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
	Fullname     string
	RoleID       int64
	IsActive     bool
	IsVerified   bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Fullname,
		arg.RoleID,
		arg.IsActive,
		arg.IsVerified,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Fullname,
		&i.RoleID,
		&i.IsActive,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

type DeleteUserParams struct {
	ID int64
}

func (q *Queries) DeleteUser(ctx context.Context, arg DeleteUserParams) error {
	_, err := q.db.ExecContext(ctx, deleteUser, arg.ID)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, fullname, role_id, is_active, is_verified, created_at, updated_at
FROM users
WHERE email = $1 LIMIT 1
`

type GetUserByEmailParams struct {
	Email string
}

func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Fullname,
		&i.RoleID,
		&i.IsActive,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, email, password_hash, fullname, role_id, is_active, is_verified, created_at, updated_at
FROM users
WHERE id = $1 LIMIT 1
`

type GetUserByIdParams struct {
	ID int64
}

func (q *Queries) GetUserById(ctx context.Context, arg GetUserByIdParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Fullname,
		&i.RoleID,
		&i.IsActive,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, fullname, role_id, is_active, is_verified, created_at, updated_at 
FROM users
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListUsersParams struct {
	Limit  int32
	Offset int32
}

type ListUsersRow struct {
	ID         int64
	Email      string
	Fullname   string
	RoleID     int64
	IsActive   bool
	IsVerified bool
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Fullname,
			&i.RoleID,
			&i.IsActive,
			&i.IsVerified,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserDetail = `-- name: UpdateUserDetail :one
UPDATE users
SET 
    fullname = $2,
    role_id = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, email, fullname, role_id, is_active, is_verified, created_at, updated_at
`

type UpdateUserDetailParams struct {
	ID       int64
	Fullname string
	RoleID   int64
}

type UpdateUserDetailRow struct {
	ID         int64
	Email      string
	Fullname   string
	RoleID     int64
	IsActive   bool
	IsVerified bool
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (q *Queries) UpdateUserDetail(ctx context.Context, arg UpdateUserDetailParams) (UpdateUserDetailRow, error) {
	row := q.db.QueryRowContext(ctx, updateUserDetail, arg.ID, arg.Fullname, arg.RoleID)
	var i UpdateUserDetailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Fullname,
		&i.RoleID,
		&i.IsActive,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserStatus = `-- name: UpdateUserStatus :exec
UPDATE users
SET 
    is_active = $2,
    is_verified = $3,
    updated_at = now()
WHERE id = $1
`

type UpdateUserStatusParams struct {
	ID         int64
	IsActive   bool
	IsVerified bool
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateUserStatus, arg.ID, arg.IsActive, arg.IsVerified)
	return err
}
